# Generated by Django 5.2.1 on 2025-12-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='cars/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(max_length=255)),
                ('doors', models.IntegerField()),
                ('passengers', models.IntegerField()),
                ('transmission', models.CharField(max_length=255)),
                ('fuel', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
