# Generated by Django 5.2.1 on 2025-12-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.IntegerField(choices=[(4, '4 Doors'), (6, '6 Doors')]),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid')]),
        ),
        migrations.AlterField(
            model_name='car',
            name='passengers',
            field=models.IntegerField(choices=[(2, '2 Passengers'), (4, '4 Passengers'), (6, '6 Passengers'), (8, '8 Passengers')]),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('semi-automatic', 'Semi-Automatic')]),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('coupe', 'Coupe')]),
        ),
    ]
